# Generated by Django 3.2.15 on 2022-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ImageField(default='stock', upload_to=''),
            preserve_default=False,
        ),
    ]
